### ISSUE TITLE
Show file selected

### ISSUE THREAD

**Issue by renato-franca** [ddutra9/print-mobile#2]
The class can select the file but can't open it.

![arquivo](https://cloud.githubusercontent.com/assets/13905375/9704523/c9160cb2-5480-11e5-86cb-390edecc75bb.JPG)

**Comment by renato-franca** [comment]
@ddutra9, how is it done in Java for desktop?? Maybe could be equal :P

**Comment by ddutra9** [comment]
Do you can use something like this example http://zacktutorials.blogspot.com.br/2014/07/android-downloading-and-viewing-pdf.html

**Comment by renato-franca** [comment]
Solved

**Comment by ddutra9** [comment]
Now I do man LOL
